import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/component/Navbar";
import Providers, { AuthProviders } from "@/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Skill Path",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProviders>
            <Navbar />
            {children}
          </AuthProviders>
        </body>
      </Providers>
    </html>
  );
}
